inherit_gem:
  theforeman-rubocop:
    - strict.yml

Layout/LineLength:
  Enabled: 111 # TODO: discuss and set this

# Don't enforce frozen string literals
Style/FrozenStringLiteralComment:
  Enabled: false
